### ISSUE TITLE
The meaning of "int2onehot"

### ISSUE THREAD

**Issue by lihuiliullh** [HKUST-KnowComp/NeuralSubgraphCounting#1]
Hi Xin:

May I know the meaning of "int2onehot" in your code? or can you give an example on how to calculate this?

Thanks.

**Comment by seanliu96** [comment]
Hi lihuiliullh,

Given an integer, we can easily convert it into another base, e.g., base 2 (binary), base 8 (octal).
If we want to encode 5 into binary, we will get 101. And we can pad unlimited zeros such as 00101.
As the domain of each digit is {0, 1}, we can further encode each digit into a one-hot vector 10 (for zero) or 01 (for one).
Hence, we will get 10,10,01,01,01 when we can call int2onehot(7, 5, base=2).
Similarly, when we set base as 5, we will get 12. And we can encode 12 into 01000,00100.

**Comment by lihuiliullh** [comment]
Thanks for the explanation. May I know why you choose this encoding method?  Is it important for the performance of the model? If I use another encoding method, e.g. using '101' to denote 5, will the performance become bad?

**Comment by seanliu96** [comment]
Hi,

It is a tradeoff between overfitting and underfitting. Using less vectors makes models unable to converge, while simple one-hot vectors, e.g., 000001000000, results in heavy overfitting.
