### ISSUE TITLE
which torch and dlg version that you saved the small dataset

### ISSUE THREAD

**Issue by balcilar** [HKUST-KnowComp/NeuralSubgraphCounting#3]
I download your small dataset, but I could not managed to load it. I tried different version of torch and dgl.
I somehow think the problem of the version problem. Please can you tell us which version of torch and dgl you used when saving the dataset?

**Comment by seanliu96** [comment]
Hi, I used pytorch 1.4.0 and dgl 0.4.3post2. Please have a try and concat me if you have further problems.

**Comment by balcilar** [comment]
Perfect!
It worked, thanks. I strongly recommend you to put your configuration file in the repository. 
Thanks indeed.

**Comment by seanliu96** [comment]
Thanks for your feedback. I have updated!
