### ISSUE TITLE
KeyError: 'return_weights'

### ISSUE THREAD

**Issue by yangop8** [HKUST-KnowComp/NeuralSubgraphCounting#5]
Hi Xin,

When I gonna finetune the model, I got the error `KeyError: 'return_weights'`.
And I read the code of `finetune.py`, but I couldn't find `return_weights` is defined in the `finetune_config`.
Could you tell me how I can debug?

Thanks a lot.

**Comment by seanliu96** [comment]
I have deleted that parameter. Please pull the latest code.

**Comment by yangop8** [comment]
Thanks, it works now!
